### ISSUE TITLE
Readme Typos

### ISSUE THREAD

**Issue by mbanushi** [fadion/aria#3]
Read through the entire Readme and came across a few typos:
1. Under "Aria Language" section:

> If features mutable and immutable values

**It** features...

2. Under "Type Conversion" section:

> Converting between types is handle in a few ways

**handled** in a ...

3. Under "Closures" section:

> Some would prefer more explicit way of calling:

... prefer **a** more explicit ...

That is all I could find, provided that I was more focused on the content than on the grammar :)

**Comment by fadion** [comment]
Thanks 👍 . I've made several typo passes, but some just like to hide in plain sight :)
